# Generated by Django 5.2 on 2025-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
