# Generated by Django 5.2 on 2025-04-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.SlugField(unique=True),
        ),
    ]
